name: CI

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run build

  test_plan:
    name: Test [plan]
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.plan.outputs.packages }}
    steps:
      - uses: actions/checkout@v4

      - uses: fuxingloh/turbo-plan@v2
        id: plan
        with:
          task: test

  test_run:
    name: Test [run]
    needs: test_plan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.test_plan.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run test --filter=${{ matrix.package }}

  test_completed:
    name: Test [completed]
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test_run
    steps:
      - run: |
          if ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }} ; then          
            exit 1
          fi

  lint_prettier:
    name: Lint [prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prettier --check .

  lint_eslint:
    name: Lint [eslint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run lint
